EXTRA_VENDOR_LIBRARIES += \
	libandroid \
	libandroid_runtime \
	libandroidfw \
	libappfuse \
	libaudioclient \
	libaudiomanager \
	libdebuggerd_client \
	libdng_sdk \
	libETC1 \
	libgraphicsenv \
	libharfbuzz_ng \
	libheif \
	libhwui \
	libicui18n \
	libicuuc \
	libimg_utils \
	libinput \
	libmedia \
	libmediadrm \
	libmediametrics \
	libmediautils \
	libmemunreachable \
	libminikin \
	libnativebridge \
	libnativehelper \
	libnativeloader \
	libnetd_client \
	libpackagelistparser \
	libpdfium \
	libprocessgroup \
	libRScpp \
	libselinux \
	libsensor \
	libskia \
	libsonivox \
	libsoundtrigger \
	libstdc++ \
	libvintf \
	libvulkan
